In [1]:
import pandas as pd
#df = pd.read_csv("FifaData\\FIFA23_official_data.csv") #Windows
df = pd.read_csv("FifaData/FIFA23_official_data.csv") # Mac

## Pregunta 1

Antes de comenzar el análisis, ¿qué información contiene nuestro dataset?

- ¿Cuántos jugadores contiene?
- ¿Cuántas variables tenemos?
- ¿Qué columnas existen?
- ¿Qué tipos de datos contiene?
- ¿Cuáles son las principales estadísticas descriptivas de las variables numéricas?

In [68]:
df.head()
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17660 entries, 0 to 17659
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        17660 non-null  int64
 1   Name                      17660 non-null  object
 2   Age                       17660 non-null  int64
 3   Photo                     17660 non-null  object
 4   Nationality               17660 non-null  object
 5   Flag                      17660 non-null  object
 6   Overall                   17660 non-null  int64
 7   Potential                 17660 non-null  int64
 8   Club                      17449 non-null  object
 9   Club Logo                 17660 non-null  object
 10  Value                     17660 non-null  object
 11  Wage                      17660 non-null  object
 12  Special                   17660 non-null  int64
 13  Preferred Foot            17660 non-null  object
 14  International Reputation  17660 non-null  float64
 15  Weak Foot                 17660 non-null  float64
 16  Skill Moves               17660 non-null  float64
 17  Work Rate                 17660 non-null  object
 18  Body Type                 17622 non-null  object
 19  Real Face                 17622 non-null  object
 20  Position                  17625 non-null  object
 21  Joined                    16562 non-null  object
 22  Loaned From               694 non-null    object
 23  Contract Valid Until      17299 non-null  object
 24  Height                    17660 non-null  object
 25  Weight                    17660 non-null  object
 26  Release Clause            16509 non-null  object
 27  Kit Number                17625 non-null  float64
 28  Best Overall Rating       21 non-null     object
dtypes: float64(4), int64(5), object(20)
memory usage: 3.9+ MB

,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Kit Number
count,17660.000000,17660.000000,17660.000000,17660.000000,17660.000000,17660.000000,17660.000000,17660.000000,17625.000000
mean,246319.424462,23.127746,63.369592,70.981200,1537.915855,1.106285,2.900340,2.297169,25.037957
std,31487.892861,4.639821,8.036268,6.529836,285.893809,0.407021,0.663523,0.754264,19.154116
min,16.000000,15.000000,43.000000,42.000000,749.000000,1.000000,1.000000,1.000000,1.000000
25%,240732.500000,20.000000,58.000000,67.000000,1387.000000,1.000000,3.000000,2.000000,11.000000
50%,257041.000000,22.000000,63.000000,71.000000,1548.000000,1.000000,3.000000,2.000000,22.000000
75%,263027.500000,26.000000,69.000000,75.000000,1727.000000,1.000000,3.000000,3.000000,32.000000
max,271340.000000,54.000000,91.000000,95.000000,2312.000000,5.000000,5.000000,5.000000,99.000000

## Pregunta 2

¿Cuál es la edad promedio de los jugadores?

Además:

- ¿Cuál es la mediana de edad?
- ¿Cuál es la edad mínima?
- ¿Cuál es la edad máxima?
- ¿Qué tan dispersas están las edades respecto al promedio?

In [69]:
df["Age"].mean()

23.127746319365798

In [70]:
df["Age"].median()

22.0

In [71]:

display(df["Age"].min())
print(df["Age"].max())
print(df["Age"].std())

15

54
4.639820579272827

## Pregunta 3

¿Qué nacionalidades tienen mayor representación en el dataset?

Además:

- ¿Cuántas nacionalidades diferentes existen?
- ¿Cuáles son las 10 nacionalidades con más jugadores?

In [72]:
df["Nationality"].value_counts().head(10)

Nationality
England        1531
Germany        1038
Spain           990
France          864
Argentina       843
Brazil          539
Italy           517
Netherlands     455
Uruguay         417
Japan           378
Name: count, dtype: int64

In [73]:
df["Nationality"].nunique()

161

## Pregunta 4

¿Quiénes son los 10 jugadores mejor evaluados?

Para cada uno, muestra al menos:

- Nombre
- Edad
- Nacionalidad
- Club
- Overall

In [74]:
df.sort_values("Overall", ascending=False).head(10)

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Real Face,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause,Kit Number,Best Overall Rating
41,188545,R. Lewandowski,33,https://cdn.sofifa.net/players/188/545/23_60.png,Poland,https://cdn.sofifa.net/flags/pl.png,91,91,FC Barcelona,https://cdn.sofifa.net/teams/241/30.png,...,Yes,"<span class=""pos pos25"">ST","Jul 18, 2022",NaN,2025,185cm,81kg,€172.2M,9.0,NaN
75,231747,K. Mbappé,23,https://cdn.sofifa.net/players/231/747/23_60.png,France,https://cdn.sofifa.net/flags/fr.png,91,95,Paris Saint-Germain,https://cdn.sofifa.net/teams/73/30.png,...,Yes,"<span class=""pos pos25"">ST","Jul 1, 2018",NaN,2025,182cm,73kg,€366.7M,7.0,NaN
124,165153,K. Benzema,34,https://cdn.sofifa.net/players/165/153/23_60.png,France,https://cdn.sofifa.net/flags/fr.png,91,91,Real Madrid CF,https://cdn.sofifa.net/teams/243/30.png,...,Yes,"<span class=""pos pos21"">CF","Jul 9, 2009",NaN,2023,185cm,81kg,€131.2M,9.0,NaN
56,158023,L. Messi,35,https://cdn.sofifa.net/players/158/023/23_60.png,Argentina,https://cdn.sofifa.net/flags/ar.png,91,91,Paris Saint-Germain,https://cdn.sofifa.net/teams/73/30.png,...,Yes,"<span class=""pos pos23"">RW","Aug 10, 2021",NaN,2023,169cm,67kg,€99.9M,30.0,NaN
3,192985,K. De Bruyne,31,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,https://cdn.sofifa.net/flags/be.png,91,91,Manchester City,https://cdn.sofifa.net/teams/10/30.png,...,Yes,"<span class=""pos pos13"">RCM","Aug 30, 2015",NaN,2025,181cm,70kg,€198.9M,17.0,NaN
100,20801,Cristiano Ronaldo,37,https://cdn.sofifa.net/players/020/801/23_60.png,Portugal,https://cdn.sofifa.net/flags/pt.png,90,90,Manchester United,https://cdn.sofifa.net/teams/11/30.png,...,Yes,"<span class=""pos pos25"">ST","Aug 27, 2021",NaN,2023,187cm,83kg,€77.9M,7.0,NaN
192,203376,V. van Dijk,30,https://cdn.sofifa.net/players/203/376/23_60.png,Netherlands,https://cdn.sofifa.net/flags/nl.png,90,90,Liverpool,https://cdn.sofifa.net/teams/9/30.png,...,Yes,"<span class=""pos pos6"">LCB","Jan 1, 2018",NaN,2025,193cm,92kg,€181.3M,4.0,NaN
14357,192119,T. Courtois,30,https://cdn.sofifa.net/players/192/119/23_60.png,Belgium,https://cdn.sofifa.net/flags/be.png,90,91,Real Madrid CF,https://cdn.sofifa.net/teams/243/30.png,...,Yes,"<span class=""pos pos0"">GK","Aug 9, 2018",NaN,2026,199cm,96kg,€191.3M,1.0,NaN
9151,167495,M. Neuer,36,https://cdn.sofifa.net/players/167/495/23_60.png,Germany,https://cdn.sofifa.net/flags/de.png,90,90,FC Bayern München,https://cdn.sofifa.net/teams/21/30.png,...,Yes,"<span class=""pos pos0"">GK","Jul 1, 2011",NaN,2024,193cm,93kg,€22.3M,1.0,NaN
25,209331,M. Salah,30,https://cdn.sofifa.net/players/209/331/23_60.png,Egypt,https://cdn.sofifa.net/flags/eg.png,90,90,Liverpool,https://cdn.sofifa.net/teams/9/30.png,...,Yes,"<span class=""pos pos23"">RW","Jul 1, 2017",NaN,2023,175cm,71kg,€213.7M,11.0,NaN

In [75]:
df.sort_values(
    "Overall", ascending=False
)[["Name", "Age", "Nationality", "Club", "Overall"]].head(10)

                    Name  Age  Nationality                 Club  Overall
41        R. Lewandowski   33       Poland         FC Barcelona       91
75             K. Mbappé   23       France  Paris Saint-Germain       91
124           K. Benzema   34       France       Real Madrid CF       91
56              L. Messi   35    Argentina  Paris Saint-Germain       91
3           K. De Bruyne   31      Belgium      Manchester City       91
100    Cristiano Ronaldo   37     Portugal    Manchester United       90
192          V. van Dijk   30  Netherlands            Liverpool       90
14357        T. Courtois   30      Belgium       Real Madrid CF       90
9151            M. Neuer   36      Germany    FC Bayern München       90
25              M. Salah   30        Egypt            Liverpool       90

## Pregunta 5

¿Qué posición tiene el mejor promedio de desempeño (`Overall`)?

Antes de responder:

- Observa cómo viene almacenada la columna `Position`.
- ¿Notas algo extraño en sus valores?
- ¿Podemos utilizarla directamente o será necesario limpiarla posteriormente?

In [76]:
df.groupby("Position")["Overall"].mean()

Position
<span class="pos pos0">GK      70.125000
<span class="pos pos10">CDM    70.162162
<span class="pos pos11">LDM    69.336207
<span class="pos pos12">RM     68.598592
<span class="pos pos13">RCM    69.270769
<span class="pos pos14">CM     68.040000
<span class="pos pos15">LCM    69.517685
<span class="pos pos16">LM     68.851449
<span class="pos pos17">RAM    74.666667
<span class="pos pos18">CAM    70.377451
<span class="pos pos19">LAM    71.142857
<span class="pos pos2">RWB     67.517647
<span class="pos pos20">RF     71.428571
<span class="pos pos21">CF     76.000000
<span class="pos pos22">LF     70.500000
<span class="pos pos23">RW     70.183099
<span class="pos pos24">RS     69.236111
<span class="pos pos25">ST     70.387283
<span class="pos pos26">LS     68.236025
<span class="pos pos27">LW     70.127517
<span class="pos pos28">SUB    63.044702
<span class="pos pos29">RES    58.235260
<span class="pos pos3">RB      68.354740
<span class="pos pos4">RCB     68.826281
<span class="pos pos5">CB      70.574074
<span class="pos pos6">LCB     68.937186
<span class="pos pos7">LB      68.263636
<span class="pos pos8">LWB     67.285714
<span class="pos pos9">RDM     68.101562
Name: Overall, dtype: float64

## Pregunta 6

¿Existe relación entre la edad de un jugador y su desempeño (`Overall`)?

- Calcula la correlación entre ambas variables.
- ¿La relación es positiva o negativa?
- ¿Es débil, moderada o fuerte?
- ¿Una correlación implica necesariamente causalidad?

In [77]:
df[["Age", "Overall"]].corr()

             Age  Overall
Age      1.00000  0.59569
Overall  0.59569  1.00000

|   Correlación | Interpretación             |
| ------------: | -------------------------- |
|          `+1` | Relación positiva perfecta |
| cerca de `+1` | Relación positiva fuerte   |
|           `0` | No hay relación lineal     |
| cerca de `-1` | Relación negativa fuerte   |
|          `-1` | Relación negativa perfecta |

## Pregunta 7

¿Cuántos jugadores utilizan el pie derecho y cuántos el izquierdo?

Además:

- ¿Qué porcentaje representa cada grupo?

In [78]:
df["Preferred Foot"].value_counts()

Preferred Foot
Right    13651
Left      4009
Name: count, dtype: int64

In [79]:
df["Preferred Foot"].value_counts(normalize=True) * 100

Preferred Foot
Right    77.298981
Left     22.701019
Name: proportion, dtype: float64

## Pregunta 8

¿Los jugadores zurdos tienen mejor evaluación promedio que los jugadores derechos?

- Compara el promedio de `Overall` para ambos grupos.
- ¿La diferencia parece importante?

In [80]:
df.groupby("Preferred Foot")["Overall"].mean()

Preferred Foot
Left     64.297830
Right    63.096989
Name: Overall, dtype: float64

## Pregunta 9

¿Quiénes son los jugadores jóvenes con mayor potencial?

Considera como jugador joven a quien tenga 21 años o menos.

Muestra al menos:

- Nombre
- Edad
- Overall
- Potential
- Club

In [81]:
jovenes = df[df["Age"] <= 21]

jovenes.sort_values(
    "Potential",
    ascending=False
)[["Name", "Age", "Overall", "Potential", "Club"]].head(10)

                 Name  Age  Overall  Potential                 Club
180        E. Haaland   21       88         94      Manchester City
214             Pedri   19       85         93         FC Barcelona
849      Vinícius Jr.   21       86         92       Real Madrid CF
70      J. Bellingham   19       84         91    Borussia Dortmund
795          F. Wirtz   19       82         91  Bayer 04 Leverkusen
698        J. Musiala   19       81         90    FC Bayern München
953   22 M. Greenwood   19       79         90    Manchester United
1544        Ansu Fati   19       79         90         FC Barcelona
697              Gavi   17       79         89         FC Barcelona
86          A. Davies   21       84         89    FC Bayern München

## Pregunta 10

¿Qué jugadores tienen mayor oportunidad de crecimiento?

Para responder:

- Crea una nueva variable que represente la diferencia entre `Potential` y `Overall`.
- Identifica a los jugadores con la mayor diferencia.
- ¿Qué significa esa diferencia en términos deportivos?

In [82]:
df["Growth"] = df["Potential"] - df["Overall"]

In [83]:
df.sort_values(
    "Growth",
    ascending=False
)[["Name", "Age", "Overall", "Potential", "Growth"]].head(10)

                Name  Age  Overall  Potential  Growth
12373      D. Lobban   16       53         79      26
14483    22 K. Smith   16       57         83      26
14989     E. Mayenda   17       53         79      26
15365    F. Valencia   17       50         75      25
16520   22 P. Lervik   16       57         82      25
15205      J. Feeney   17       55         80      25
14675  22 A. Denholm   17       52         77      25
8409      22 D. Gore   16       57         82      25
17450    22 C. Walsh   16       52         77      25
15169      L. Harvey   17       53         78      25

## Pregunta 11

¿Qué clubes tienen, en promedio, los jugadores mejor evaluados?

Antes de sacar conclusiones:

- Calcula el promedio de `Overall` por club.
- Calcula también cuántos jugadores tiene cada club en el dataset.
- ¿Tiene sentido comparar clubes con cantidades muy diferentes de jugadores?

In [84]:
df.groupby("Club")["Overall"].mean()

Club
1. FC Heidenheim 1846        63.333333
1. FC Kaiserslautern         61.894737
1. FC Köln                   69.043478
1. FC Magdeburg              62.173913
1. FC Nürnberg               63.235294
                               ...
İstanbul Başakşehir FK       68.500000
İstanbulspor                 60.071429
İttifak Holding Konyaspor    64.214286
ŁKS Łódź                     56.000000
Śląsk Wrocław                59.750000
Name: Overall, Length: 926, dtype: float64

In [85]:
df.groupby("Club")["Overall"].mean().sort_values(ascending=False).head(10)

Club
Messina                   80.000000
RB Bragantino             79.750000
Clube Atlético Mineiro    79.750000
Palmeiras                 79.750000
Inter                     78.666667
AFC Richmond              78.066667
Villarreal CF             78.040000
Paris Saint-Germain       77.897436
Juventus                  77.750000
FC Bayern München         77.393939
Name: Overall, dtype: float64

In [86]:
df.groupby("Club")["Overall"].count().sort_values(ascending=False)

Club
Manchester United           66
Arsenal                     47
FC Barcelona                46
Newcastle United            45
Atlético de Madrid          45
                            ..
Zagłębie Sosnowiec           1
Padova                       1
US Créteil-Lusitanos         1
Évian Thonon Gaillard FC     1
SV Mattersburg               1
Name: Overall, Length: 926, dtype: int64

In [87]:
df.groupby("Club")["Overall"].agg(["mean", "count"])

                                mean  count
Club
1. FC Heidenheim 1846      63.333333     18
1. FC Kaiserslautern       61.894737     19
1. FC Köln                 69.043478     23
1. FC Magdeburg            62.173913     23
1. FC Nürnberg             63.235294     17
...                              ...    ...
İstanbul Başakşehir FK     68.500000     22
İstanbulspor               60.071429     14
İttifak Holding Konyaspor  64.214286     14
ŁKS Łódź                   56.000000      4
Śląsk Wrocław              59.750000     16

[926 rows x 2 columns]

In [88]:
clubes = df.groupby("Club")["Overall"].agg(["mean", "count"])

In [89]:
clubes.sort_values("count", ascending=False).head(10)

                              mean  count
Club
Manchester United        69.696970     66
Arsenal                  72.702128     47
FC Barcelona             76.195652     46
Newcastle United         68.311111     45
Atlético de Madrid       74.933333     45
Wolverhampton Wanderers  65.340909     44
Gangwon FC               54.500000     42
Chelsea                  74.476190     42
Caracas Fútbol Club      61.439024     41
PSV                      70.853659     41

In [90]:
clubes.sort_values("mean", ascending=False).head(10)

                             mean  count
Club
Messina                 80.000000      1
RB Bragantino           79.750000      4
Clube Atlético Mineiro  79.750000      4
Palmeiras               79.750000      4
Inter                   78.666667     33
AFC Richmond            78.066667     15
Villarreal CF           78.040000     25
Paris Saint-Germain     77.897436     39
Juventus                77.750000     32
FC Bayern München       77.393939     33

## Pregunta 12

¿Nuestro dataset contiene valores faltantes?

- ¿Qué columnas tienen más valores faltantes?
- ¿Todos los valores faltantes representan necesariamente un problema?
- ¿Qué podría significar, por ejemplo, que `Loaned From` esté vacío?

In [91]:
df.isnull().sum()

ID                              0
Name                            0
Age                             0
Photo                           0
Nationality                     0
Flag                            0
Overall                         0
Potential                       0
Club                          211
Club Logo                       0
Value                           0
Wage                            0
Special                         0
Preferred Foot                  0
International Reputation        0
Weak Foot                       0
Skill Moves                     0
Work Rate                       0
Body Type                      38
Real Face                      38
Position                       35
Joined                       1098
Loaned From                 16966
Contract Valid Until          361
Height                          0
Weight                          0
Release Clause               1151
Kit Number                     35
Best Overall Rating         17639
Growth                          0
dtype: int64

In [92]:
df.isnull().sum().sort_values(ascending=False)

Best Overall Rating         17639
Loaned From                 16966
Release Clause               1151
Joined                       1098
Contract Valid Until          361
Club                          211
Body Type                      38
Real Face                      38
Position                       35
Kit Number                     35
Age                             0
Photo                           0
Nationality                     0
ID                              0
Preferred Foot                  0
Special                         0
Wage                            0
Value                           0
Club Logo                       0
Potential                       0
Overall                         0
Flag                            0
Name                            0
Weak Foot                       0
Skill Moves                     0
Work Rate                       0
International Reputation        0
Height                          0
Weight                          0
Growth                          0
dtype: int64

## Pregunta 13

¿Podemos calcular directamente el valor promedio de mercado de los jugadores utilizando la columna `Value`?

- Observa primero cómo vienen almacenados los valores.
- ¿La columna es numérica o de texto?
- ¿Qué elementos habría que eliminar o transformar antes de calcular un promedio?

In [93]:
df["Value"].head(10)

0       €91M
1     €78.5M
2     €46.5M
3    €107.5M
4     €89.5M
5    €105.5M
6     €55.5M
7     €28.5M
8     €30.5M
9     €82.5M
Name: Value, dtype: object

In [94]:
df["Value"].dtype

dtype('O')

In [95]:
def convertir_valor(valor):
    valor = valor.replace("€", "")

    if "M" in valor:
        return float(valor.replace("M", "")) * 1_000_000

    elif "K" in valor:
        return float(valor.replace("K", "")) * 1_000

    else:
        return float(valor)

In [96]:
df["ValueNumeric"] = df["Value"].apply(convertir_valor)

In [97]:
df[["Name", "Value", "ValueNumeric"]].head(10)

              Name    Value  ValueNumeric
0      L. Goretzka     €91M    91000000.0
1  Bruno Fernandes   €78.5M    78500000.0
2         M. Acuña   €46.5M    46500000.0
3     K. De Bruyne  €107.5M   107500000.0
4       N. Barella   €89.5M    89500000.0
5       J. Kimmich  €105.5M   105500000.0
6         D. Alaba   €55.5M    55500000.0
7      22 Paulinho   €28.5M    28500000.0
8           E. Can   €30.5M    30500000.0
9     João Cancelo   €82.5M    82500000.0

In [98]:
df["ValueNumeric"].mean()

2739788.3918459797

In [99]:
df["ValueNumeric"].mean() / 1_000_000

2.7397883918459796

## Pregunta 14

¿Podemos calcular directamente el salario promedio de los jugadores utilizando la columna `Wage`?

- Observa cómo vienen representados los salarios.
- ¿Qué transformaciones serían necesarias antes de analizarlos numéricamente?

In [100]:
df["Wage"].head(10)

0    €115K
1    €190K
2     €46K
3    €350K
4    €110K
5    €130K
6    €220K
7     €61K
8     €63K
9    €250K
Name: Wage, dtype: object

In [101]:
def convertir_salario(salario):
    salario = salario.replace("€", "")

    if "K" in salario:
        return float(salario.replace("K", "")) * 1_000

    return float(salario)

In [102]:
df["WageNumeric"] = df["Wage"].apply(convertir_salario)

In [103]:
df[["Name", "Wage", "WageNumeric"]].head(10)

              Name   Wage  WageNumeric
0      L. Goretzka  €115K     115000.0
1  Bruno Fernandes  €190K     190000.0
2         M. Acuña   €46K      46000.0
3     K. De Bruyne  €350K     350000.0
4       N. Barella  €110K     110000.0
5       J. Kimmich  €130K     130000.0
6         D. Alaba  €220K     220000.0
7      22 Paulinho   €61K      61000.0
8           E. Can   €63K      63000.0
9     João Cancelo  €250K     250000.0

In [104]:
df["WageNumeric"].mean()

8189.807474518686

## Pregunta 15

¿Cómo vienen almacenadas las variables `Height` y `Weight`?

- ¿Son valores numéricos?
- ¿Qué unidades aparecen?
- ¿Qué tendríamos que hacer para poder calcular promedios, mínimos, máximos o correlaciones con estas variables?

In [105]:
df[["Height", "Weight"]].head(10)

  Height Weight
0  189cm   82kg
1  179cm   69kg
2  172cm   69kg
3  181cm   70kg
4  172cm   68kg
5  177cm   75kg
6  180cm   78kg
7  183cm   80kg
8  186cm   86kg
9  182cm   74kg

In [106]:
df[["Height", "Weight"]].dtypes

Height    object
Weight    object
dtype: object

In [107]:
df["HeightNumeric"] = (
    df["Height"]
    .str.replace("cm", "")
    .astype(float)
)

In [108]:
df["WeightNumeric"] = (
    df["Weight"]
    .str.replace("kg", "")
    .astype(float)
)

In [109]:
df[
    ["Name", "Height", "HeightNumeric", "Weight", "WeightNumeric"]
].head(10)

              Name Height  HeightNumeric Weight  WeightNumeric
0      L. Goretzka  189cm          189.0   82kg           82.0
1  Bruno Fernandes  179cm          179.0   69kg           69.0
2         M. Acuña  172cm          172.0   69kg           69.0
3     K. De Bruyne  181cm          181.0   70kg           70.0
4       N. Barella  172cm          172.0   68kg           68.0
5       J. Kimmich  177cm          177.0   75kg           75.0
6         D. Alaba  180cm          180.0   78kg           78.0
7      22 Paulinho  183cm          183.0   80kg           80.0
8           E. Can  186cm          186.0   86kg           86.0
9     João Cancelo  182cm          182.0   74kg           74.0

In [111]:
df["HeightNumeric"].describe()

count    17660.000000
mean       180.893431
std          6.962486
min        149.000000
25%        176.000000
50%        181.000000
75%        186.000000
max        206.000000
Name: HeightNumeric, dtype: float64

In [112]:
df["WeightNumeric"].describe()

count    17660.000000
mean        74.326161
std          6.982741
min         48.000000
25%         70.000000
50%         74.000000
75%         79.000000
max        110.000000
Name: WeightNumeric, dtype: float64

In [113]:
df[
    ["HeightNumeric", "WeightNumeric", "Overall"]
].corr()

               HeightNumeric  WeightNumeric   Overall
HeightNumeric       1.000000       0.764012  0.059272
WeightNumeric       0.764012       1.000000  0.162321
Overall             0.059272       0.162321  1.000000